name: YX-PolymerizedCrystal
version: 1.0.2
main: memory520.polymerizedcrystal.PolymerizedCrystal
api-version: 1.15
softdepend:
  - MythicMobs

commands:
  pc:
    description: 打开聚合界面

permissions:
  pc.open.use:
    default: true
  pc.reload.admin:
    default: op